import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SettingsModalProvider } from "@/components/settings/SettingsModalProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { THEME_STORAGE_KEY } from "@/lib/themeStorage";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeBootstrapScript = `(function(){try{var k=${JSON.stringify(THEME_STORAGE_KEY)};var v=localStorage.getItem(k);var d=document.documentElement;var dark=v==="dark"||(v!=="light"&&window.matchMedia("(prefers-color-scheme: dark)").matches);d.classList.toggle("dark",dark);}catch(e){}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-background"
      style={{
        border: "none",
        borderWidth: 0,
        borderStyle: "none",
        margin: 0,
        padding: 0,
        outline: "none",
        boxShadow: "none",
      }}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: themeBootstrapScript }}
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kalam:wght@300;400;700&family=Nanum+Pen+Script&family=Patrick+Hand&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen`}
        style={{
          border: "none",
          borderWidth: 0,
          borderStyle: "none",
          margin: 0,
          padding: 0,
          outline: "none",
          boxShadow: "none",
        }}
      >
        {/* Covers stray 1px hairlines at the top of the viewport (browser / compositing seams) */}
        <div
          aria-hidden
          className="pointer-events-none fixed left-0 right-0 top-0 z-[2147483647] h-[3px] bg-background"
        />
        <ThemeProvider>
          <SettingsModalProvider>
            <Navbar />
            {children}
          </SettingsModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
